---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "minio"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "minio"
  template:
    metadata:
      labels:
        app: "minio"
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: minio
          image: quay.io/minio/minio
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: password
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - mountPath: /data
              name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: "minio"
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
  selector:
    app: "minio"
