---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: minio
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - minio.k8s.reddec.net
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
